{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include .Chart.Name . }}
type: Opaque
data:
  sensitive_key: {{ .Files.Get "sops_secrets/sensitive_key" | b64enc | quote }}
{{- end }}